name: fax-ui
environments:
  - name: integration
    path: "../opta.yml"
modules:
  - name: ui
    public_uri: "ui.{parent.domain}"
    type: k8s-service
    port:
      http: 3000
    image: AUTO
    env_vars:
      - name: AWS_REGION
        value: us-east-1
      - name: NODE_LOCAL_PORT
        value: '8080'
      - name: NODE_DOCKER_PORT
        value: '8080'
      - name: CLIENT_ORIGIN
        value: http://127.0.0.1:3000
      - name: CLIENT_API_BASE_URL
        value: http://127.0.0.1:8080
      - name: REACT_LOCAL_PORT
        value: '3000'
      - name: REACT_DOCKER_PORT
        value: '80'
    secrets:
      - NODE_LOCAL_PORT
      - NODE_DOCKER_PORT
      - CLIENT_ORIGIN
      - CLIENT_API_BASE_URL
      - REACT_LOCAL_PORT
      - REACT_DOCKER_PORT
    resource_request:
      cpu: 500
      memory: 1024